### ISSUE TITLE
When roo returns `Too many experiments will be returned with the query: *` acas does not return the message to the user

### ISSUE THREAD

**Issue by brianbolt** [mcneilco/acas#449]
When searching with * tomcat will a message about returning too many results. ACAS does not handle this response.

ACAS should return the error from ROO to the user:

```Too many experiments will be returned with the query: *```

```acas_1       | 2018-01-19T22:25:06.123Z - info: http://localhost:8080/acas/api/v1/experiments/search?q=*&userName=regressiontester
tomcat_1     | 19 Jan 2018 22:25:06 91574001 [http-bio-8080-exec-28] WARN  com.labsynch.labseer.service.ExperimentServiceImpl  - Query for '*' detected. Determining if number of results is too many.
tomcat_1     | 19 Jan 2018 22:25:06 91574002 [http-bio-8080-exec-28] ERROR com.labsynch.labseer.api.ApiExperimentController  - Caught error in experiment search
tomcat_1     | com.labsynch.labseer.exceptions.TooManyResultsException: Too many experiments will be returned with the query: *
tomcat_1     |     at com.labsynch.labseer.service.ExperimentServiceImpl.findExperimentsByGenericMetaDataSearch_aroundBody22(ExperimentServiceImpl.java:1057)
acas_1       | 2018-01-19T22:25:06.130Z - info: got ajax error
tomcat_1     |     at com.labsynch.labseer.service.ExperimentServiceImpl$AjcClosure23.run(ExperimentServiceImpl.java:1)
acas_1       | 2018-01-19T22:25:06.130Z - info: null
tomcat_1     |     at org.springframework.transaction.aspectj.AbstractTransactionAspect.ajc$around$org_springframework_transaction_aspectj_AbstractTransactionAspect$1$2a73e96cproceed(AbstractTransactionAspect.aj:59)
acas_1       | 2018-01-19T22:25:06.130Z - info: com.labsynch.labseer.exceptions.TooManyResultsException: Too many experiments will be returned with the query: *
tomcat_1     |     at org.springframework.transaction.aspectj.AbstractTransactionAspect$AbstractTransactionAspect$1.proceedWithInvocation(AbstractTransactionAspect.aj:65)
tomcat_1     |     at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260)
tomcat_1     |     at org.springframework.transaction.aspectj.AbstractTransactionAspect.ajc$around$org_springframework_transaction_aspectj_AbstractTransactionAspect$1$2a73e96c(AbstractTransactionAspect.aj:63)
tomcat_1     |     at com.labsynch.labseer.service.ExperimentServiceImpl.findExperimentsByGenericMetaDataSearch(ExperimentServiceImpl.java:1042)
tomcat_1     |     at com.labsynch.labseer.service.ExperimentServiceImpl.findExperimentsByGenericMetaDataSearch_aroundBody20(ExperimentServiceImpl.java:1012)
tomcat_1     |     at com.labsynch.labseer.service.ExperimentServiceImpl$AjcClosure21.run(ExperimentServiceImpl.java:1)```

**Comment by brianbolt** [comment]
Currently the max limit returned from search is hardcoded to 1000
